name = "docker-registry-proxy"
main = "worker.js"
compatibility_date = "2025-12-29"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[env.production]
routes = [
  { pattern = "hub.hxorz.com/*", custom_domain = true }
]
